# Copyright 2025 Louis Rokitta
generate_content:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: mistral_ai_api
    prompt:
      required: true
      selector:
        text:
          multiline: true
      example: "Hello, how can I help you?"
    filenames:
      selector:
        text:
          multiline: true
      example: |
        - /path/to/file1.txt
        - /path/to/file2.txt
